'use client';
import { useEffect, useState } from 'react';
import { api } from '@/src/lib/api';
import { shortMoney } from '@/src/lib/format';
import { Card, ErrorBox, Kpi, Loading, Progress, SectionTitle, Status } from './ui';

export function Dashboard({onNavigate}:{onNavigate:(s:any)=>void}){
 const [data,setData]=useState<any>(null); const [error,setError]=useState('');
 const load=async()=>{setError('');try{const [summary,projection,works,stock,suppliers]=await Promise.all([api.get<any>('/api/dashboard/summary'),api.get<any[]>('/api/dashboard/cash-projection?days=180'),api.get<any[]>('/api/reports/work-profitability'),api.get<any[]>('/api/reports/current-stock'),api.get<any[]>('/api/reports/supplier-balances')]);setData({summary,projection,works,stock,suppliers})}catch(e:any){setError(e.message)}};
 useEffect(()=>{load()},[]);
 if(error)return <ErrorBox message={error} onRetry={load}/>; if(!data)return <Loading/>;
 const s=data.summary; const projPoints=[0,30,60,90,180].map(d=>{const target=new Date();target.setDate(target.getDate()+d);const iso=target.toISOString().slice(0,10);let row=data.projection.find((x:any)=>String(x.day).slice(0,10)===iso);if(!row&&d===0)row={projected_cash:s.cash_balance};return {label:d===0?'Hoy':`${d}d`,value:Number(row?.projected_cash??s.cash_balance)}}); const max=Math.max(1,...projPoints.map(x=>Math.abs(x.value)));
 const lowStock=data.stock.filter((x:any)=>Number(x.current_stock)<Number(x.minimum_stock));
 return <div className="page-stack"><div className="kpi-grid four"><Kpi label="Caja disponible" value={shortMoney(s.cash_balance)} note="Saldo actual consolidado" tone="good"/><Kpi label="Por cobrar" value={shortMoney(s.receivables)} note={`${shortMoney(s.overdue_receivables)} vencidos`} tone={Number(s.overdue_receivables)>0?'warn':'good'}/><Kpi label="Por pagar" value={shortMoney(s.payables)} note={`${shortMoney(s.overdue_payables)} vencidos`} tone={Number(s.overdue_payables)>0?'warn':'neutral'}/><Kpi label="Posición neta" value={shortMoney(s.net_position)} note="Caja + créditos − obligaciones" tone={Number(s.net_position)>=0?'good':'bad'}/></div>
 <div className="two-col wide-left"><Card><SectionTitle title="Caja proyectada" subtitle="Cobros y pagos previstos" action={<button className="link-button" onClick={()=>onNavigate('finance')}>Ver finanzas →</button>}/><div className="cash-chart">{projPoints.map(p=><div className="bar-wrap" key={p.label}><div className="bar-value">{shortMoney(p.value)}</div><div className="bar-shell"><div className="bar" style={{height:`${Math.max(18,Math.abs(p.value)/max*150)}px`}}/></div><span>{p.label}</span></div>)}</div></Card><Card><SectionTitle title="Salud operativa"/><div className="health-list"><div><span>Obras activas</span><strong>{s.active_works}</strong><Status tone="blue">En curso</Status></div><div><span>Total contratado</span><strong>{shortMoney(s.total_contracted)}</strong></div><div><span>Costos fijos / mes</span><strong>{shortMoney(s.monthly_fixed_costs)}</strong></div><div><span>Stock bajo</span><strong>{lowStock.length}</strong><Status tone={lowStock.length?'yellow':'green'}>{lowStock.length?'Revisar':'OK'}</Status></div></div></Card></div>
 <div className="two-col"><Card><SectionTitle title="Obras" subtitle="Rentabilidad y avance" action={<button className="link-button" onClick={()=>onNavigate('works')}>Administrar →</button>}/>{data.works.length===0?<div className="empty-state">Todavía no hay obras cargadas.</div>:<div className="list-stack">{data.works.slice(0,4).map((w:any)=><div className="work-mini" key={w.id}><div className="work-mini-head"><div><b>{w.code}</b><span>{w.name}</span></div><Status tone={w.status==='activo'?'blue':'green'}>{w.status}</Status></div><div className="dual-progress"><span>Avance</span><Progress value={w.progress_percent}/><span>Margen</span><Progress value={Number(w.margin_ratio||0)*100}/></div></div>)}</div>}</Card><Card><SectionTitle title="Alertas" subtitle="Lo que requiere atención"/><div className="alerts">{Number(s.overdue_receivables)>0&&<div className="alert red"><b>Cobros vencidos</b><span>{shortMoney(s.overdue_receivables)}</span></div>}{Number(s.overdue_payables)>0&&<div className="alert red"><b>Pagos vencidos</b><span>{shortMoney(s.overdue_payables)}</span></div>}{lowStock.slice(0,2).map((x:any)=><div className="alert yellow" key={x.id}><b>Stock bajo · {x.name}</b><span>{x.current_stock} {x.unit} disponibles · mínimo {x.minimum_stock}</span></div>)}{data.suppliers.filter((x:any)=>Number(x.balance)>0).slice(0,2).map((x:any)=><div className="alert blue" key={x.id}><b>Saldo proveedor · {x.name}</b><span>{shortMoney(x.balance)}</span></div>)}{Number(s.overdue_receivables)===0&&Number(s.overdue_payables)===0&&lowStock.length===0&&<div className="alert blue"><b>Sin alertas críticas</b><span>Los datos actuales no muestran vencidos ni stock bajo.</span></div>}</div></Card></div></div>
}
