'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/src/lib/api';
import { dateAR, money } from '@/src/lib/format';
import type { FieldSpec, ResourceSpec } from '@/src/lib/resources';
import { Card, Empty, ErrorBox, Loading, SectionTitle, Status } from './ui';

type Lookup = Record<string, Record<string,string>>;

export function ResourceManager({spec, subtitle, compact=false, hideTitle=false, onRowClick}:{spec:ResourceSpec;subtitle?:string;compact?:boolean;hideTitle?:boolean;onRowClick?:(row:any)=>void}){
 const [rows,setRows]=useState<any[]>([]); const [lookups,setLookups]=useState<Lookup>({}); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [query,setQuery]=useState(''); const [editing,setEditing]=useState<any|null>(null); const [modal,setModal]=useState(false); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const rels=Array.from(new Set([...spec.fields,...spec.columns].flatMap((x:any)=>x.relation?[x.relation.table]:[])));const [data,...relData]=await Promise.all([api.list(spec.table,'?limit=500'),...rels.map(r=>api.list(r,'?limit=500'))]);setRows(data);const dict:Lookup={};rels.forEach((r,i)=>{dict[r]={};(relData[i]||[]).forEach((x:any)=>dict[r][x.id]=String(x.name??x.code??x.description??x.purchase_number??x.concept??x.id));});setLookups(dict);}catch(e:any){setError(e.message||String(e));}finally{setLoading(false)}},[spec]);
 useEffect(()=>{load()},[load]);
 const filtered=useMemo(()=>{if(!query.trim())return rows;const q=query.toLowerCase();return rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q))},[rows,query]);
 const openNew=()=>{setEditing(null);setModal(true)}; const openEdit=(r:any)=>{setEditing(r);setModal(true)};
 async function remove(r:any){if(!confirm(`¿Eliminar este ${spec.singular}? Esta acción no se puede deshacer.`))return;try{await api.remove(spec.table,r.id);await load()}catch(e:any){alert(e.message)}}
 async function submit(data:Record<string,any>){setSaving(true);try{if(editing)await api.update(spec.table,editing.id,data);else await api.create(spec.table,data);setModal(false);setEditing(null);await load()}catch(e:any){alert(e.message)}finally{setSaving(false)}}
 async function generateReceivables(r:any){if(!confirm(`¿Generar el cronograma de cobros de ${r.name}? Solo se crearán cuotas que todavía no existan.`))return;try{const result=await api.post<any>(`/api/works/${r.id}/generate-receivables`);alert(`Cronograma generado. Nuevas cuotas: ${result.created_count}. Ya existentes: ${result.skipped_count}.`)}catch(e:any){alert(e.message)}}
 return <div className="page-stack resource-block">{!hideTitle&&<SectionTitle title={spec.title} subtitle={subtitle} action={<button className="primary-button" onClick={openNew}>+ Nuevo</button>}/>} {hideTitle&&<div className="inline-actions"><button className="primary-button" onClick={openNew}>+ Nuevo</button></div>}
 {error?<ErrorBox message={error} onRetry={load}/>:loading?<Loading/>:<Card><div className="table-toolbar"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={`Buscar en ${spec.title.toLowerCase()}…`}/><span className="record-count">{filtered.length} registros</span></div>{filtered.length===0?<Empty text={`Todavía no hay ${spec.title.toLowerCase()}.`}/>:<div className="table-wrap"><table><thead><tr>{spec.columns.map(c=><th key={c.key}>{c.label}</th>)}<th>Acciones</th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} className={onRowClick?'clickable-row':''} onClick={()=>onRowClick?.(r)}>{spec.columns.map(c=><td key={c.key}>{renderCell(r[c.key],c,lookups)}</td>)}<td><div className="row-actions">{spec.table==='works'&&r.type==='servicio_mensual'&&<button className="mini-button" onClick={(e)=>{e.stopPropagation();generateReceivables(r)}}>Generar cobros</button>}<button className="mini-button" onClick={(e)=>{e.stopPropagation();openEdit(r)}}>Editar</button><button className="mini-button danger-text" onClick={(e)=>{e.stopPropagation();remove(r)}}>Eliminar</button></div></td></tr>)}</tbody></table></div>}</Card>}
 {modal&&<EditorModal spec={spec} initial={editing} lookups={lookups} onClose={()=>setModal(false)} onSubmit={submit} saving={saving}/>}</div>
}

function renderCell(v:any,c:any,lookups:Lookup){if(c.relation)return lookups[c.relation.table]?.[v]||'—';if(c.kind==='money')return <b>{money(v)}</b>;if(c.kind==='date')return dateAR(v);if(c.kind==='percent')return `${Number(v||0).toFixed(0)}%`;if(c.kind==='boolean')return <Status tone={v?'green':'gray'}>{v?'Activo':'Inactivo'}</Status>;if(c.kind==='status'){const s=String(v||'');const tone=s.includes('cancel')||s.includes('rechaz')?'red':s.includes('pend')?'yellow':s.includes('activo')||s.includes('aprob')||s.includes('recib')||s.includes('cobrado')||s.includes('pagado')?'green':'blue';return <Status tone={tone as any}>{s||'—'}</Status>}return v===null||v===undefined||v===''?'—':String(v)}

function EditorModal({spec,initial,lookups,onClose,onSubmit,saving}:{spec:ResourceSpec;initial:any;lookups:Lookup;onClose:()=>void;onSubmit:(d:any)=>void;saving:boolean}){
 const defaults:Record<string,any>={};spec.fields.forEach(f=>{let v=initial?.[f.name]; if(v===undefined||v===null){if(f.type==='boolean')v=true;else if(f.type==='number')v=0;else if(f.type==='date'&&(f.name.includes('date')||f.name==='valid_from'))v=new Date().toISOString().slice(0,10);else v='';} if(f.type==='date'&&v)v=String(v).slice(0,10);defaults[f.name]=v});
 const [form,setForm]=useState(defaults);
 function change(f:FieldSpec,v:any){setForm(x=>{const next:any={...x,[f.name]:v};if(spec.table==='works'&&f.name==='type'&&v==='servicio_mensual'){if(!next.billing_frequency)next.billing_frequency='mensual';if(!next.billing_day)next.billing_day=10;}if(spec.table==='works'&&f.name==='type'&&v!=='servicio_mensual'){next.billing_frequency='';next.monthly_amount='';next.billing_day='';}return next})}
 function submit(e:React.FormEvent){e.preventDefault();const out:Record<string,any>={};for(const f of spec.fields){if(f.showWhen&&form[f.showWhen.field]!==f.showWhen.equals){out[f.name]=null;continue}let v=form[f.name];if(v===''&&!f.required){out[f.name]=null;continue}if(f.type==='number')v=v===''?null:Number(v);if(f.type==='boolean')v=Boolean(v);out[f.name]=v;}onSubmit(out)}
 const visibleFields=spec.fields.filter(f=>!f.showWhen||form[f.showWhen.field]===f.showWhen.equals);
 return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div className="modal"><div className="modal-head"><div><span className="eyebrow">{initial?'EDITAR':'NUEVO'}</span><h2>{initial?`Editar ${spec.singular}`:`Nuevo ${spec.singular}`}</h2></div><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid">{visibleFields.map(f=><Field key={f.name} f={f} value={form[f.name]} onChange={v=>change(f,v)} lookups={lookups}/>)}</div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button type="submit" className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar'}</button></div></form></div></div>
}
function Field({f,value,onChange,lookups}:{f:FieldSpec;value:any;onChange:(v:any)=>void;lookups:Lookup}){const cls=f.type==='textarea'?'field full':'field';return <label className={cls}><span>{f.label}{f.required?' *':''}</span>{f.type==='textarea'?<textarea value={value??''} onChange={e=>onChange(e.target.value)} rows={3}/>:f.type==='boolean'?<input type="checkbox" checked={Boolean(value)} onChange={e=>onChange(e.target.checked)}/>:f.type==='select'?<select value={value??''} required={f.required} onChange={e=>onChange(e.target.value)}><option value="">Seleccionar…</option>{f.options?.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}{f.relation&&Object.entries(lookups[f.relation.table]||{}).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>:<input type={f.type==='number'?'number':f.type==='date'?'date':'text'} step={f.step||'any'} required={f.required} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>}
