'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/src/lib/api';
import { dateAR, money } from '@/src/lib/format';
import { Card, Empty, ErrorBox, Kpi, Loading, SectionTitle, Status } from './ui';

type Props={serviceId:string;onBack:()=>void};
const today=()=>new Date().toISOString().slice(0,10);

export function ServiceDetail({serviceId,onBack}:Props){
 const [data,setData]=useState<any|null>(null); const [accounts,setAccounts]=useState<any[]>([]); const [error,setError]=useState(''); const [loading,setLoading]=useState(true); const [tab,setTab]=useState<'summary'|'billing'|'payments'|'documents'>('summary');
 const [invoicePeriod,setInvoicePeriod]=useState<any|null>(null); const [invoice,setInvoice]=useState({document_number:'',issue_date:today(),due_date:'',notes:''});
 const [payRow,setPayRow]=useState<any|null>(null); const [payment,setPayment]=useState({account_id:'',amount:'',payment_date:today(),notes:''});
 const [upload,setUpload]=useState<any|null>(null); const [saving,setSaving]=useState(false);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [d,a]=await Promise.all([api.get<any>(`/api/services/${serviceId}/detail`),api.list<any>('accounts','?limit=500')]);setData(d);setAccounts(a.filter((x:any)=>x.is_active!==false));}catch(e:any){setError(e.message||String(e))}finally{setLoading(false)}},[serviceId]);
 useEffect(()=>{void load()},[load]);
 if(error)return <ErrorBox message={error} onRetry={load}/>; if(loading||!data)return <Loading/>;
 const s=data.service,m=data.metrics,periods=data.periods||[],docs=data.documents||[];
 const billed=periods.filter((p:any)=>p.receivable_id);
 const pending=periods.filter((p:any)=>!p.receivable_id);
 return <div className="page-stack">
  <div className="work-detail-head"><button className="ghost-button" onClick={onBack}>← Servicios</button><div><span className="eyebrow">{s.code}</span><h1>{s.name}</h1><p>{s.client_name||'Sin cliente'} · {s.service_type==='mensual'?'Servicio mensual':'Servicio puntual'}</p></div><Status tone={s.status==='activo'?'green':s.status==='cancelado'?'red':'blue'}>{s.status}</Status></div>
  <div className="kpi-grid four"><Kpi label="Valor contratado" value={money(m.contract_amount)}/><Kpi label="Facturado" value={money(m.invoiced)}/><Kpi label="Cobrado" value={money(m.collected)} tone="good"/><Kpi label="Pendiente de cobro" value={money(m.pending_collection)} tone={Number(m.pending_collection)>0?'warn':'good'}/></div>
  <div className="tabs standalone work-tabs">{[['summary','Resumen'],['billing','Facturación'],['payments','Cobros'],['documents','Documentación']].map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as any)}>{label}</button>)}</div>
  {tab==='summary'&&<Summary service={s} metrics={m} periods={periods}/>} 
  {tab==='billing'&&<Billing periods={periods} onInvoice={(p:any)=>{setInvoicePeriod(p);setInvoice({document_number:'',issue_date:today(),due_date:String(p.due_date||'').slice(0,10),notes:''})}} onUpload={(p:any)=>setUpload({type:'factura',title:`Factura ${p.document_number||p.period_number}`,related_type:'invoice',related_id:p.receivable_id})} docs={docs}/>} 
  {tab==='payments'&&<Payments rows={billed} onPay={(p:any)=>{const due=Math.max(0,Number(p.amount||0)-Number(p.paid_amount||0));setPayRow(p);setPayment({account_id:accounts[0]?.id||'',amount:String(due),payment_date:today(),notes:''})}} onUpload={(p:any)=>setUpload({type:'comprobante_pago',title:`Comprobante de cobro ${p.document_number||p.period_number}`,related_type:'payment_receivable',related_id:p.receivable_id})}/>} 
  {tab==='documents'&&<Documents docs={docs} onUpload={()=>setUpload({type:'contrato',title:'Contrato',related_type:null,related_id:null})} onView={async(d:any)=>{try{const r=await api.get<any>(`/api/service-documents/${d.id}/signed-url`);window.open(r.url,'_blank')}catch(e:any){alert(e.message)}}}/>} 
  {invoicePeriod&&<InvoiceModal row={invoicePeriod} form={invoice} setForm={setInvoice} saving={saving} close={()=>setInvoicePeriod(null)} submit={async()=>{setSaving(true);try{await api.post(`/api/services/${serviceId}/periods/${invoicePeriod.id}/invoice`,{...invoice,due_date:invoice.due_date||null});setInvoicePeriod(null);await load()}catch(e:any){alert(e.message)}finally{setSaving(false)}}}/>} 
  {payRow&&<PaymentModal row={payRow} accounts={accounts} form={payment} setForm={setPayment} saving={saving} close={()=>setPayRow(null)} submit={async()=>{setSaving(true);try{await api.post(`/api/services/${serviceId}/receivables/${payRow.receivable_id}/payments`,{...payment,amount:Number(payment.amount)});setPayRow(null);await load()}catch(e:any){alert(e.message)}finally{setSaving(false)}}}/>} 
  {upload&&<UploadModal serviceId={serviceId} initial={upload} close={()=>setUpload(null)} done={async()=>{setUpload(null);await load()}}/>}
 </div>
}

function Summary({service:s,metrics:m,periods}:{service:any;metrics:any;periods:any[]}){return <div className="two-col"><Card><SectionTitle title="Datos del servicio"/><div className="detail-grid"><Info l="Cliente" v={s.client_name}/><Info l="Modalidad" v={s.service_type}/><Info l="Monto por período" v={money(s.billing_amount)}/><Info l="Duración" v={s.duration_months?`${s.duration_months} meses`:'—'}/><Info l="Inicio" v={dateAR(s.start_date)}/><Info l="Fin" v={dateAR(s.end_date)}/><Info l="Día previsto de cobro" v={s.billing_day||'—'}/><Info l="Contrato" v={s.is_contract?'Sí':'No'}/></div></Card><Card><SectionTitle title="Estado comercial"/><div className="health-list"><div><span>Períodos totales</span><strong>{periods.length}</strong></div><div><span>Períodos facturados</span><strong>{periods.filter((x:any)=>x.receivable_id).length}</strong></div><div><span>Pendiente de facturar</span><strong>{money(m.pending_invoice)}</strong></div><div><span>Pendiente de cobrar</span><strong>{money(m.pending_collection)}</strong></div></div></Card></div>}
function Info({l,v}:{l:string;v:any}){return <div className="info-cell"><span>{l}</span><b>{v??'—'}</b></div>}

function Billing({periods,onInvoice,onUpload,docs}:{periods:any[];onInvoice:(p:any)=>void;onUpload:(p:any)=>void;docs:any[]}){return <Card><SectionTitle title="Facturación por período" subtitle="Cada mes se factura una sola vez. La factura genera automáticamente una cuenta por cobrar."/><div className="table-wrap"><table><thead><tr><th>Período</th><th>Vigencia</th><th>Vencimiento</th><th>Monto</th><th>Factura</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{periods.map(p=>{const hasPdf=docs.some((d:any)=>d.related_type==='invoice'&&d.related_id===p.receivable_id);return <tr key={p.id}><td><b>Mes {p.period_number}</b></td><td>{dateAR(p.period_start)} → {dateAR(p.period_end)}</td><td>{dateAR(p.due_date)}</td><td><b>{money(p.amount)}</b></td><td>{p.document_number||'—'}</td><td>{p.receivable_id?<Status tone={p.receivable_status==='cobrado'?'green':p.receivable_status==='parcial'?'blue':'yellow'}>{p.receivable_status||'facturado'}</Status>:<Status tone="gray">Pendiente</Status>}</td><td><div className="row-actions">{!p.receivable_id?<button className="mini-button" onClick={()=>onInvoice(p)}>Facturar</button>:<button className="mini-button" onClick={()=>onUpload(p)}>{hasPdf?'Reemplazar / agregar PDF':'Subir factura PDF'}</button>}</div></td></tr>})}</tbody></table></div></Card>}

function Payments({rows,onPay,onUpload}:{rows:any[];onPay:(p:any)=>void;onUpload:(p:any)=>void}){if(rows.length===0)return <Card><Empty text="Todavía no hay facturas para cobrar."/></Card>;return <Card><SectionTitle title="Cobros" subtitle="Podés registrar cobros parciales o totales y elegir en qué cuenta ingresó el dinero."/><div className="table-wrap"><table><thead><tr><th>Factura</th><th>Período</th><th>Facturado</th><th>Cobrado</th><th>Saldo</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(p=>{const balance=Math.max(0,Number(p.amount||0)-Number(p.paid_amount||0));return <tr key={p.id}><td><b>{p.document_number||'—'}</b></td><td>Mes {p.period_number}</td><td>{money(p.amount)}</td><td>{money(p.paid_amount)}</td><td><b>{money(balance)}</b></td><td><Status tone={balance<=0?'green':Number(p.paid_amount)>0?'blue':'yellow'}>{balance<=0?'Cobrado':Number(p.paid_amount)>0?'Parcial':'Pendiente'}</Status></td><td><div className="row-actions">{balance>0&&<button className="mini-button" onClick={()=>onPay(p)}>Registrar cobro</button>}{Number(p.paid_amount)>0&&<button className="mini-button" onClick={()=>onUpload(p)}>Subir comprobante</button>}</div></td></tr>})}</tbody></table></div></Card>}

function Documents({docs,onUpload,onView}:{docs:any[];onUpload:()=>void;onView:(d:any)=>void}){return <Card><SectionTitle title="Documentación" subtitle="Contrato, propuesta/presupuesto, orden de compra y otros PDFs." action={<button className="primary-button" onClick={onUpload}>+ Subir documento</button>}/>{docs.length===0?<Empty text="Todavía no hay documentos cargados."/>:<div className="document-grid">{docs.map(d=><div className="document-card" key={d.id}><span className="doc-type">{String(d.document_type||'documento').replaceAll('_',' ')}</span><b>{d.title}</b><small>{d.file_name}</small><button className="mini-button" onClick={()=>onView(d)}>Ver PDF</button></div>)}</div>}</Card>}

function InvoiceModal({row,form,setForm,saving,close,submit}:any){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">FACTURAR</span><h2>Mes {row.period_number} · {money(row.amount)}</h2></div><button className="close-button" onClick={close}>×</button></div><div className="form-grid"><label className="field"><span>Número de factura *</span><input value={form.document_number} onChange={e=>setForm({...form,document_number:e.target.value})}/></label><label className="field"><span>Fecha emisión</span><input type="date" value={form.issue_date} onChange={e=>setForm({...form,issue_date:e.target.value})}/></label><label className="field"><span>Vencimiento</span><input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></label><label className="field full"><span>Notas</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modal-actions"><button className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={saving||!form.document_number.trim()} onClick={submit}>{saving?'Guardando…':'Crear factura'}</button></div></div></div>}

function PaymentModal({row,accounts,form,setForm,saving,close,submit}:any){return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">COBRO</span><h2>{row.document_number||`Mes ${row.period_number}`}</h2></div><button className="close-button" onClick={close}>×</button></div><div className="form-grid"><label className="field"><span>Cuenta *</span><select value={form.account_id} onChange={e=>setForm({...form,account_id:e.target.value})}><option value="">Seleccionar…</option>{accounts.map((a:any)=><option value={a.id} key={a.id}>{a.name} · {a.currency}</option>)}</select></label><label className="field"><span>Monto *</span><input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label className="field"><span>Fecha</span><input type="date" value={form.payment_date} onChange={e=>setForm({...form,payment_date:e.target.value})}/></label><label className="field full"><span>Notas</span><textarea rows={3} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label></div><div className="modal-actions"><button className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={saving||!form.account_id||Number(form.amount)<=0} onClick={submit}>{saving?'Guardando…':'Registrar cobro'}</button></div></div></div>}

function UploadModal({serviceId,initial,close,done}:any){const [type,setType]=useState(initial.type||'contrato');const [title,setTitle]=useState(initial.title||'Documento');const [file,setFile]=useState<File|null>(null);const [saving,setSaving]=useState(false);async function send(){if(!file)return;setSaving(true);try{const fd=new FormData();fd.append('service_id',serviceId);fd.append('document_type',type);fd.append('title',title);if(initial.related_type)fd.append('related_type',initial.related_type);if(initial.related_id)fd.append('related_id',initial.related_id);fd.append('file',file);await api.upload('/api/service-documents/upload',fd);await done()}catch(e:any){alert(e.message)}finally{setSaving(false)}}return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><span className="eyebrow">DOCUMENTO</span><h2>Subir PDF</h2></div><button className="close-button" onClick={close}>×</button></div><div className="form-grid"><label className="field"><span>Tipo</span><select value={type} onChange={e=>setType(e.target.value)}><option value="contrato">Contrato</option><option value="presupuesto">Propuesta / presupuesto</option><option value="orden_compra">Orden de compra</option><option value="factura">Factura</option><option value="comprobante_pago">Comprobante de pago</option><option value="otro">Otro</option></select></label><label className="field"><span>Título</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full"><span>Archivo PDF</span><input type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="modal-actions"><button className="ghost-button" onClick={close}>Cancelar</button><button className="primary-button" disabled={saving||!file} onClick={send}>{saving?'Subiendo…':'Subir PDF'}</button></div></div></div>}
