import { Card, SectionTitle, Status, shortMoney, money } from './ui';
export function Suppliers({suppliers,movements,selectedId,onSelect}:any){
 const sel=suppliers.find((s:any)=>s.id===selectedId); if(sel) return <SupplierDetail s={sel} movements={movements.filter((m:any)=>m.supplier===sel.id)} onBack={()=>onSelect(null)}/>;
 return <div className="page-stack"><SectionTitle title="Proveedores y contratistas" subtitle="Cuenta corriente, horas trabajadas, tarifas y pagos." action={<button className="primary-button">+ Nuevo proveedor</button>}/>
 <div className="kpi-grid three"><Simple label="Saldo total pendiente" value={shortMoney(suppliers.reduce((a:number,s:any)=>a+s.balance,0))}/><Simple label="Deuda vencida" value={shortMoney(suppliers.reduce((a:number,s:any)=>a+s.overdue,0))}/><Simple label="Trabajado este mes" value={shortMoney(suppliers.reduce((a:number,s:any)=>a+s.monthWorked,0))}/></div>
 <Card><div className="table-wrap"><table><thead><tr><th>Proveedor / contratado</th><th>Tipo</th><th>Servicio</th><th>Saldo</th><th>Vencido</th><th>Mes trabajado</th><th>Último pago</th></tr></thead><tbody>{suppliers.map((s:any)=><tr className="clickable" key={s.id} onClick={()=>onSelect(s.id)}><td><b>{s.name}</b><span className="cell-sub">{s.id}</span></td><td><Status tone="blue">{s.kind}</Status></td><td>{s.service}</td><td><b>{shortMoney(s.balance)}</b></td><td>{s.overdue? <Status tone="red">{shortMoney(s.overdue)}</Status>:'-'}</td><td>{shortMoney(s.monthWorked)}</td><td>{s.lastPayment}</td></tr>)}</tbody></table></div></Card></div>
}
function SupplierDetail({s,movements,onBack}:any){return <div className="page-stack"><button className="link-button" onClick={onBack}>← Volver a proveedores</button><div className="detail-head"><div><span className="eyebrow">{s.id} · {s.kind}</span><h2>{s.name}</h2><p>{s.service}</p></div><Status tone="green">{s.status}</Status></div><div className="kpi-grid four"><Simple label="Saldo pendiente" value={shortMoney(s.balance)}/><Simple label="Vencido" value={shortMoney(s.overdue)}/><Simple label="Trabajado este mes" value={shortMoney(s.monthWorked)}/><Simple label="Último pago" value={s.lastPayment}/></div><Card><SectionTitle title="Cuenta corriente" subtitle="Horas, jornadas, viajes, unidades o montos fijos." action={<button className="primary-button">+ Cargar trabajo</button>}/><div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Obra</th><th>Concepto</th><th>Cantidad</th><th>Tarifa</th><th>Importe</th><th>Validación</th><th>Pagado</th></tr></thead><tbody>{movements.map((m:any,i:number)=><tr key={i}><td>{m.date}</td><td>{m.work}</td><td>{m.concept}</td><td>{m.qty} {m.unit}</td><td>{money(m.price)}</td><td><b>{money(m.amount)}</b></td><td><Status tone={m.approved?'green':'yellow'}>{m.approved?'Aprobado':'Pendiente'}</Status></td><td>{money(m.paid)}</td></tr>)}</tbody></table></div></Card></div>}
function Simple({label,value}:{label:string,value:string}){return <Card className="kpi"><span className="kpi-label">{label}</span><strong>{value}</strong></Card>}
