'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/src/lib/api';
import { dateAR, money, pct, shortMoney } from '@/src/lib/format';
import { Card, Empty, ErrorBox, Kpi, Loading, SectionTitle, Status } from './ui';

type Props={workId:string;onBack:()=>void};
type Tab='summary'|'items'|'budget'|'costs'|'certificates'|'invoices'|'documents'|'suppliers';

export function WorkDetail({workId,onBack}:Props){
 const [tab,setTab]=useState<Tab>('summary'); const [d,setD]=useState<any>(null); const [error,setError]=useState('');
 const [suppliers,setSuppliers]=useState<any[]>([]); const [accounts,setAccounts]=useState<any[]>([]);
 const load=useCallback(async()=>{try{setError('');const [detail,s,a]=await Promise.all([api.get<any>(`/api/works/${workId}/detail`),api.list<any>('suppliers','?limit=500'),api.list<any>('accounts','?limit=500')]);setD(detail);setSuppliers(s);setAccounts(a)}catch(e:any){setError(e.message)}},[workId]);
 useEffect(()=>{load()},[load]); if(error)return <ErrorBox message={error} onRetry={load}/>; if(!d)return <Loading/>;
 const w=d.work,m=d.metrics;
 return <div className="page-stack work-detail"><div className="work-detail-head"><button className="ghost-button" onClick={onBack}>← Volver a obras</button><div><span className="eyebrow">{w.code}</span><h1>{w.name}</h1><p>{w.client_name} · {w.type?.replaceAll('_',' ')}</p></div><Status tone={w.status==='activo'?'green':w.status==='finalizado'?'blue':'yellow'}>{w.status}</Status></div>
 <div className="kpi-grid six"><Kpi label="Contrato" value={shortMoney(w.contract_amount)}/><Kpi label="Costo real" value={shortMoney(m.real_cost)} tone={Number(m.real_cost)>Number(w.estimated_cost||0)&&Number(w.estimated_cost)>0?'warn':'neutral'}/><Kpi label="Resultado" value={shortMoney(m.projected_result)} tone={Number(m.projected_result)>=0?'good':'bad'}/><Kpi label="Avance" value={`${Number(w.progress_percent||0).toFixed(0)}%`}/><Kpi label="Facturado" value={shortMoney(m.invoiced)}/><Kpi label="Cobrado" value={shortMoney(m.collected)}/></div>
 <div className="tabs standalone work-tabs">{([['summary','Resumen'],['items','Ítems / avance'],['budget','Presupuesto'],['costs','Costos'],['certificates','Certificados'],['invoices','Facturación'],['documents','Documentos'],['suppliers','Proveedores']] as [Tab,string][]).map(([id,l])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{l}</button>)}</div>
 {tab==='summary'&&<Summary d={d}/>} {tab==='items'&&<Items workId={workId} rows={d.items} reload={load}/>} {tab==='budget'&&<Budget workId={workId} rows={d.budget_items} costs={d.costs} reload={load}/>} {tab==='costs'&&<Costs workId={workId} rows={d.costs} suppliers={suppliers} accounts={accounts} reload={load}/>} {tab==='certificates'&&<Certificates workId={workId} rows={d.certificates} reload={load}/>} {tab==='invoices'&&<Invoices workId={workId} rows={d.receivables} reload={load}/>} {tab==='documents'&&<Documents workId={workId} rows={d.documents} reload={load}/>} {tab==='suppliers'&&<SupplierView costs={d.costs}/>} </div>
}

function Summary({d}:{d:any}){const w=d.work,m=d.metrics;const budget=Number(w.estimated_cost||0), real=Number(m.real_cost||0);return <div className="two-col"><Card><SectionTitle title="Estado de la obra"/><div className="detail-grid"><Info l="Inicio" v={dateAR(w.start_date)}/><Info l="Fin" v={dateAR(w.end_date)}/><Info l="Costo estimado" v={money(w.estimated_cost)}/><Info l="Costo real" v={money(real)}/><Info l="Desvío costo" v={money(real-budget)}/><Info l="Presupuesto consumido" v={budget?pct(real/budget):'—'}/><Info l="Pendiente de cobro" v={money(m.pending_collection)}/><Info l="Pagado a terceros" v={money(m.paid)}/></div></Card><Card><SectionTitle title="Lectura rápida"/><div className="health-list"><div><span>Avance físico</span><strong>{Number(w.progress_percent||0).toFixed(1)}%</strong></div><div><span>Presupuesto consumido</span><strong>{budget?pct(real/budget):'—'}</strong><Status tone={budget&&real/budget>.9?'red':budget&&real/budget>.7?'yellow':'green'}>{budget&&real/budget>.9?'Atención':'Controlado'}</Status></div><div><span>Margen actual</span><strong>{Number(w.contract_amount)?pct(Number(m.projected_result)/Number(w.contract_amount)):'—'}</strong></div><div><span>Documentos</span><strong>{d.documents.length}</strong></div></div></Card></div>}
function Info({l,v}:{l:string;v:any}){return <div className="info-cell"><span>{l}</span><b>{v??'—'}</b></div>}

function Items({workId,rows,reload}:{workId:string;rows:any[];reload:()=>void}){const [open,setOpen]=useState(false);const [edit,setEdit]=useState<any>(null);const save=async(f:any)=>{if(edit)await api.update('work_items',edit.id,{...f,work_id:workId});else await api.create('work_items',{...f,work_id:workId});setOpen(false);setEdit(null);reload()};return <Card><SectionTitle title="Ítems y avance ponderado" subtitle="El avance global se recalcula automáticamente según el peso de cada ítem." action={<button className="primary-button" onClick={()=>{setEdit(null);setOpen(true)}}>+ Ítem</button>}/>{rows.length===0?<Empty text="Todavía no hay ítems de obra."/>:<div className="table-wrap"><table><thead><tr><th>Ítem</th><th>Descripción</th><th>Presupuesto</th><th>Peso</th><th>Avance</th><th>Aporte</th><th>Estado</th><th/></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{r.code||'—'}</td><td><b>{r.description}</b></td><td>{money(r.budget_amount)}</td><td>{Number(r.weight_percent).toFixed(1)}%</td><td>{Number(r.progress_percent).toFixed(1)}%</td><td><b>{(Number(r.weight_percent)*Number(r.progress_percent)/100).toFixed(1)}%</b></td><td><Status tone={r.status==='completado'?'green':r.status==='en_ejecucion'?'blue':'gray'}>{r.status}</Status></td><td><button className="mini-button" onClick={()=>{setEdit(r);setOpen(true)}}>Editar</button></td></tr>)}</tbody></table></div>}{open&&<SimpleModal title={edit?'Editar ítem':'Nuevo ítem'} initial={edit||{quantity:1,unit_price:0,weight_percent:0,progress_percent:0,status:'pendiente'}} fields={[['code','Código','text'],['description','Descripción','text'],['unit','Unidad','text'],['quantity','Cantidad','number'],['unit_price','Precio unitario','number'],['weight_percent','Peso %','number'],['progress_percent','Avance %','number'],['status','Estado','select:pendiente|en_ejecucion|completado|cancelado'],['notes','Observaciones','text']]} onClose={()=>setOpen(false)} onSave={save}/>}</Card>}

function Budget({workId,rows,costs,reload}:{workId:string;rows:any[];costs:any[];reload:()=>void}){const [open,setOpen]=useState(false);const byCat=useMemo(()=>{const o:Record<string,number>={};costs.filter((x:any)=>x.payment_status!=='anulado').forEach((x:any)=>o[x.category]=(o[x.category]||0)+Number(x.amount||0));return o},[costs]);const save=async(f:any)=>{await api.create('work_budget_items',{...f,work_id:workId});setOpen(false);reload()};return <Card><SectionTitle title="Presupuesto interno" subtitle="Compará cada rubro presupuestado contra su costo real." action={<button className="primary-button" onClick={()=>setOpen(true)}>+ Rubro</button>}/>{rows.length===0?<Empty text="Todavía no cargaste el desglose del presupuesto."/>:<div className="table-wrap"><table><thead><tr><th>Rubro</th><th>Descripción</th><th>Presupuestado</th><th>Real</th><th>Desvío</th></tr></thead><tbody>{rows.map((r:any)=>{const real=byCat[r.category]||0;return <tr key={r.id}><td><b>{r.category}</b></td><td>{r.description||'—'}</td><td>{money(r.budget_amount)}</td><td>{money(real)}</td><td className={real>Number(r.budget_amount)?'danger-text':''}><b>{money(real-Number(r.budget_amount))}</b></td></tr>})}</tbody></table></div>}{open&&<SimpleModal title="Nuevo rubro" initial={{budget_amount:0}} fields={[['category','Categoría','text'],['description','Descripción','text'],['budget_amount','Monto presupuestado','number'],['notes','Notas','text']]} onClose={()=>setOpen(false)} onSave={save}/>}</Card>}

function Costs({workId,rows,suppliers,accounts,reload}:{workId:string;rows:any[];suppliers:any[];accounts:any[];reload:()=>void}){const [open,setOpen]=useState(false),[pay,setPay]=useState<any>(null);const save=async(f:any)=>{await api.post(`/api/works/${workId}/costs`,{...f,supplier_id:f.supplier_id||null});setOpen(false);reload()};const payNow=async(f:any)=>{await api.post(`/api/works/${workId}/costs/${pay.id}/pay`,{account_id:f.account_id,payment_date:f.payment_date,notes:f.notes||null});setPay(null);reload()};return <Card><SectionTitle title="Costos de obra" subtitle="Los costos con proveedor generan una cuenta por pagar; pagarlos genera la salida de caja." action={<button className="primary-button" onClick={()=>setOpen(true)}>+ Agregar costo</button>}/>{rows.length===0?<Empty text="Todavía no hay costos imputados."/>:<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Concepto</th><th>Rubro</th><th>Proveedor</th><th>Factura</th><th>Monto</th><th>Estado</th><th/></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{dateAR(r.cost_date)}</td><td><b>{r.concept}</b></td><td>{r.category}</td><td>{r.supplier_name||'—'}</td><td>{r.invoice_number||'—'}</td><td><b>{money(r.amount)}</b></td><td><Status tone={r.payment_status==='pagado'?'green':r.payment_status==='pendiente'?'yellow':'blue'}>{r.payment_status}</Status></td><td>{r.payment_status!=='pagado'&&r.payment_status!=='anulado'&&<button className="mini-button" onClick={()=>setPay(r)}>Pagar</button>}</td></tr>)}</tbody></table></div>}{open&&<CostModal suppliers={suppliers} onClose={()=>setOpen(false)} onSave={save}/>} {pay&&<PayModal accounts={accounts} cost={pay} onClose={()=>setPay(null)} onSave={payNow}/>}</Card>}

function Certificates({workId,rows,reload}:{workId:string;rows:any[];reload:()=>void}){const [open,setOpen]=useState(false);const save=async(f:any)=>{await api.create('work_certificates',{...f,work_id:workId});setOpen(false);reload()};return <Card><SectionTitle title="Certificaciones" subtitle="Registro económico de certificados; el PDF se carga en Documentos." action={<button className="primary-button" onClick={()=>setOpen(true)}>+ Certificado</button>}/>{rows.length===0?<Empty text="Sin certificados cargados."/>:<div className="table-wrap"><table><thead><tr><th>Nº</th><th>Período</th><th>Avance</th><th>Bruto</th><th>Retención</th><th>Neto</th><th>Estado</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><b>{r.certificate_number}</b></td><td>{dateAR(r.period_from)} – {dateAR(r.period_to)}</td><td>{r.progress_percent??'—'}%</td><td>{money(r.gross_amount)}</td><td>{money(r.retention_amount)}</td><td><b>{money(r.net_amount)}</b></td><td><Status tone={r.status==='aprobado'||r.status==='facturado'?'green':r.status==='rechazado'?'red':'yellow'}>{r.status}</Status></td></tr>)}</tbody></table></div>}{open&&<SimpleModal title="Nuevo certificado" initial={{gross_amount:0,retention_amount:0,status:'borrador'}} fields={[['certificate_number','Nº certificado','text'],['period_from','Desde','date'],['period_to','Hasta','date'],['progress_percent','Avance %','number'],['gross_amount','Monto bruto','number'],['retention_amount','Retención','number'],['status','Estado','select:borrador|presentado|aprobado|rechazado|facturado'],['notes','Notas','text']]} onClose={()=>setOpen(false)} onSave={save}/>}</Card>}

function Invoices({workId,rows,reload}:{workId:string;rows:any[];reload:()=>void}){const [open,setOpen]=useState(false);const save=async(f:any)=>{await api.post(`/api/works/${workId}/invoices`,f);setOpen(false);reload()};return <Card><SectionTitle title="Facturación al cliente" subtitle="Cada factura crea una cuenta por cobrar vinculada a esta obra." action={<button className="primary-button" onClick={()=>setOpen(true)}>+ Factura</button>}/>{rows.length===0?<Empty text="Todavía no hay facturas/cuentas por cobrar."/>:<div className="table-wrap"><table><thead><tr><th>Emisión</th><th>Factura</th><th>Concepto</th><th>Vence</th><th>Monto</th><th>Estado</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td>{dateAR(r.issue_date)}</td><td><b>{r.document_number||'—'}</b></td><td>{r.description}</td><td>{dateAR(r.due_date)}</td><td><b>{money(r.amount)}</b></td><td><Status tone={r.status==='cobrado'?'green':r.status==='pendiente'?'yellow':'blue'}>{r.status}</Status></td></tr>)}</tbody></table></div>}{open&&<SimpleModal title="Nueva factura" initial={{issue_date:new Date().toISOString().slice(0,10),amount:0}} fields={[['document_number','Número de factura','text'],['description','Concepto','text'],['issue_date','Fecha emisión','date'],['due_date','Vencimiento','date'],['amount','Monto','number'],['notes','Notas','text']]} onClose={()=>setOpen(false)} onSave={save}/>}</Card>}

function Documents({workId,rows,reload}:{workId:string;rows:any[];reload:()=>void}){const [open,setOpen]=useState(false);const upload=async(fd:FormData)=>{await api.upload('/api/work-documents/upload',fd);setOpen(false);reload()};const view=async(id:string)=>{const r=await api.get<any>(`/api/work-documents/${id}/signed-url`);if(r.url)window.open(r.url,'_blank')};return <Card><SectionTitle title="Documentación PDF" subtitle="Presupuestos, contratos, certificados, facturas, remitos y documentación técnica." action={<button className="primary-button" onClick={()=>setOpen(true)}>+ Subir PDF</button>}/>{rows.length===0?<Empty text="Todavía no hay documentación."/>:<div className="document-grid">{rows.map((r:any)=><div className="document-card" key={r.id}><span className="doc-type">{r.document_type.replaceAll('_',' ')}</span><b>{r.title}</b><small>{r.file_name}</small><small>{dateAR(r.document_date)}</small><button className="mini-button" onClick={()=>view(r.id)}>Ver PDF</button></div>)}</div>}{open&&<UploadModal workId={workId} onClose={()=>setOpen(false)} onSave={upload}/>}</Card>}

function SupplierView({costs}:{costs:any[]}){const rows=useMemo(()=>{const m:Record<string,any>={};costs.filter(x=>x.supplier_id&&x.payment_status!=='anulado').forEach(x=>{const k=x.supplier_id;m[k]??={id:k,name:x.supplier_name||'Proveedor',generated:0,paid:0};m[k].generated+=Number(x.amount||0);if(x.payment_status==='pagado')m[k].paid+=Number(x.amount||0)});return Object.values(m)},[costs]);return <Card><SectionTitle title="Proveedores de esta obra"/>{rows.length===0?<Empty text="No hay proveedores asociados a costos de la obra."/>:<div className="table-wrap"><table><thead><tr><th>Proveedor</th><th>Generado</th><th>Pagado</th><th>Pendiente</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.id}><td><b>{r.name}</b></td><td>{money(r.generated)}</td><td>{money(r.paid)}</td><td><b>{money(r.generated-r.paid)}</b></td></tr>)}</tbody></table></div>}</Card>}

function SimpleModal({title,initial,fields,onClose,onSave}:{title:string;initial:any;fields:any[];onClose:()=>void;onSave:(x:any)=>Promise<void>}){const [f,setF]=useState<any>({...initial});const [saving,setSaving]=useState(false);const submit=async(e:any)=>{e.preventDefault();setSaving(true);try{await onSave(f)}catch(x:any){alert(x.message)}finally{setSaving(false)}};return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>{title}</h2><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={submit}><div className="form-grid">{fields.map(([k,l,t])=><label className="field" key={k}><span>{l}</span>{String(t).startsWith('select:')?<select value={f[k]??''} onChange={e=>setF({...f,[k]:e.target.value})}><option value="">Seleccionar…</option>{String(t).slice(7).split('|').map((o:string)=><option key={o}>{o}</option>)}</select>:<input type={t==='number'?'number':t==='date'?'date':'text'} step="any" value={f[k]??''} onChange={e=>setF({...f,[k]:t==='number'?Number(e.target.value):e.target.value})}/>}</label>)}</div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Guardando…':'Guardar'}</button></div></form></div></div>}
function CostModal({suppliers,onClose,onSave}:{suppliers:any[];onClose:()=>void;onSave:(x:any)=>Promise<void>}){const [f,setF]=useState<any>({cost_date:new Date().toISOString().slice(0,10),category:'materiales',quantity:1,unit_price:0,payment_status:'pendiente'});return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Agregar costo</h2><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={async e=>{e.preventDefault();try{await onSave(f)}catch(x:any){alert(x.message)}}}><div className="form-grid"><label className="field"><span>Fecha</span><input type="date" value={f.cost_date} onChange={e=>setF({...f,cost_date:e.target.value})}/></label><label className="field"><span>Proveedor / contratista</span><select value={f.supplier_id||''} onChange={e=>setF({...f,supplier_id:e.target.value})}><option value="">Sin proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="field"><span>Rubro</span><select value={f.category} onChange={e=>setF({...f,category:e.target.value})}>{['materiales','contratistas','mano_obra','combustible','transporte','alquiler','equipos','viaticos','servicios','impuestos','otros'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Concepto</span><input value={f.concept||''} onChange={e=>setF({...f,concept:e.target.value})}/></label><label className="field"><span>Cantidad</span><input type="number" step="any" value={f.quantity} onChange={e=>setF({...f,quantity:Number(e.target.value)})}/></label><label className="field"><span>Unidad</span><input value={f.unit||''} onChange={e=>setF({...f,unit:e.target.value})}/></label><label className="field"><span>Precio unitario</span><input type="number" step="any" value={f.unit_price} onChange={e=>setF({...f,unit_price:Number(e.target.value)})}/></label><label className="field"><span>Vencimiento</span><input type="date" value={f.due_date||''} onChange={e=>setF({...f,due_date:e.target.value||null})}/></label><label className="field"><span>Factura proveedor</span><input value={f.invoice_number||''} onChange={e=>setF({...f,invoice_number:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Guardar costo</button></div></form></div></div>}
function PayModal({accounts,cost,onClose,onSave}:{accounts:any[];cost:any;onClose:()=>void;onSave:(x:any)=>Promise<void>}){const [f,setF]=useState<any>({account_id:'',payment_date:new Date().toISOString().slice(0,10)});return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Pagar {cost.concept}</h2><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={async e=>{e.preventDefault();try{await onSave(f)}catch(x:any){alert(x.message)}}}><p className="modal-note">Se registrará una salida de caja por <b>{money(cost.amount)}</b>.</p><div className="form-grid"><label className="field"><span>Cuenta *</span><select required value={f.account_id} onChange={e=>setF({...f,account_id:e.target.value})}><option value="">Seleccionar…</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name} ({a.currency})</option>)}</select></label><label className="field"><span>Fecha pago</span><input type="date" value={f.payment_date} onChange={e=>setF({...f,payment_date:e.target.value})}/></label></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button">Confirmar pago</button></div></form></div></div>}
function UploadModal({workId,onClose,onSave}:{workId:string;onClose:()=>void;onSave:(fd:FormData)=>Promise<void>}){const [type,setType]=useState('presupuesto'),[title,setTitle]=useState(''),[file,setFile]=useState<File|null>(null),[saving,setSaving]=useState(false);return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><h2>Subir documentación</h2><button className="close-button" onClick={onClose}>×</button></div><form onSubmit={async e=>{e.preventDefault();if(!file)return;const fd=new FormData();fd.append('work_id',workId);fd.append('document_type',type);fd.append('title',title||file.name);fd.append('file',file);setSaving(true);try{await onSave(fd)}catch(x:any){alert(x.message)}finally{setSaving(false)}}}><div className="form-grid"><label className="field"><span>Tipo</span><select value={type} onChange={e=>setType(e.target.value)}>{['presupuesto','contrato','certificacion','factura_cliente','factura_proveedor','remito','plano','memoria_tecnica','acta','otro'].map(x=><option key={x}>{x}</option>)}</select></label><label className="field"><span>Título</span><input value={title} onChange={e=>setTitle(e.target.value)}/></label><label className="field full"><span>Archivo PDF *</span><input required type="file" accept="application/pdf,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div><div className="modal-actions"><button type="button" className="ghost-button" onClick={onClose}>Cancelar</button><button className="primary-button" disabled={saving}>{saving?'Subiendo…':'Subir PDF'}</button></div></form></div></div>}
