export type FieldType = 'text'|'number'|'date'|'textarea'|'select'|'boolean';
export type FieldSpec = { name:string; label:string; type?:FieldType; required?:boolean; options?: {value:string;label:string}[]; relation?: {table:string; label:string}; step?:string; showWhen?: {field:string; equals:any}; };
export type ColumnSpec = { key:string; label:string; kind?:'money'|'date'|'percent'|'boolean'|'status'; relation?: {table:string; label:string}; };
export type ResourceSpec = { table:string; title:string; singular:string; fields:FieldSpec[]; columns:ColumnSpec[] };

export const specs: Record<string, ResourceSpec> = {
 clients:{table:'clients',title:'Clientes',singular:'cliente',fields:[
  {name:'name',label:'Razón social / nombre',required:true},{name:'tax_id',label:'CUIT'},{name:'contact_name',label:'Contacto'},{name:'email',label:'Email'},{name:'phone',label:'Teléfono'},{name:'address',label:'Dirección'},{name:'notes',label:'Notas',type:'textarea'},{name:'is_active',label:'Activo',type:'boolean'}],
  columns:[{key:'name',label:'Cliente'},{key:'tax_id',label:'CUIT'},{key:'contact_name',label:'Contacto'},{key:'phone',label:'Teléfono'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 works:{table:'works',title:'Obras y contratos',singular:'obra',fields:[
  {name:'code',label:'Código',required:true},
  {name:'client_id',label:'Cliente',type:'select',required:true,relation:{table:'clients',label:'name'}},
  {name:'name',label:'Nombre',required:true},
  {name:'description',label:'Descripción',type:'textarea'},
  {name:'type',label:'Tipo',type:'select',options:['obra','servicio_mensual','mantenimiento','venta','alquiler','otro'].map(x=>({value:x,label:x.replaceAll('_',' ')}))},
  {name:'billing_frequency',label:'Frecuencia de facturación',type:'select',showWhen:{field:'type',equals:'servicio_mensual'},options:[{value:'mensual',label:'Mensual'},{value:'bimestral',label:'Bimestral'},{value:'trimestral',label:'Trimestral'},{value:'anual',label:'Anual'}]},
  {name:'monthly_amount',label:'Monto mensual',type:'number',step:'0.01',showWhen:{field:'type',equals:'servicio_mensual'}},
  {name:'billing_day',label:'Día previsto de cobro',type:'number',step:'1',showWhen:{field:'type',equals:'servicio_mensual'}},
  {name:'status',label:'Estado',type:'select',options:['presupuesto','activo','pausado','finalizado','cancelado'].map(x=>({value:x,label:x}))},
  {name:'start_date',label:'Inicio',type:'date'},
  {name:'end_date',label:'Fin',type:'date'},
  {name:'contract_amount',label:'Valor total del contrato',type:'number',step:'0.01'},
  {name:'estimated_cost',label:'Costo estimado',type:'number',step:'0.01'},
  {name:'progress_percent',label:'Avance %',type:'number',step:'0.01'},
  {name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'code',label:'Código'},{key:'name',label:'Obra / contrato'},{key:'client_id',label:'Cliente',relation:{table:'clients',label:'name'}},{key:'status',label:'Estado',kind:'status'},{key:'progress_percent',label:'Avance',kind:'percent'},{key:'monthly_amount',label:'Mensual',kind:'money'},{key:'billing_frequency',label:'Frecuencia'},{key:'contract_amount',label:'Contrato',kind:'money'},{key:'estimated_cost',label:'Costo estimado',kind:'money'}]},
 suppliers:{table:'suppliers',title:'Proveedores y contratistas',singular:'proveedor',fields:[
  {name:'name',label:'Nombre / razón social',required:true},{name:'tax_id',label:'CUIT'},{name:'type',label:'Tipo',type:'select',options:['proveedor','contratista','ambos'].map(x=>({value:x,label:x}))},{name:'contact_name',label:'Contacto'},{name:'email',label:'Email'},{name:'phone',label:'Teléfono'},{name:'address',label:'Dirección'},{name:'notes',label:'Notas',type:'textarea'},{name:'is_active',label:'Activo',type:'boolean'}],
  columns:[{key:'name',label:'Proveedor / contratista'},{key:'type',label:'Tipo',kind:'status'},{key:'tax_id',label:'CUIT'},{key:'contact_name',label:'Contacto'},{key:'phone',label:'Teléfono'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 supplier_rates:{table:'supplier_rates',title:'Tarifas',singular:'tarifa',fields:[
  {name:'supplier_id',label:'Proveedor',type:'select',required:true,relation:{table:'suppliers',label:'name'}},{name:'concept',label:'Concepto',required:true},{name:'unit',label:'Unidad',type:'select',options:['hora','jornada','viaje','unidad','metro','kg','tonelada','litro','monto_fijo','otro'].map(x=>({value:x,label:x}))},{name:'unit_price',label:'Precio unitario',type:'number',required:true},{name:'valid_from',label:'Vigente desde',type:'date'},{name:'valid_to',label:'Vigente hasta',type:'date'},{name:'is_active',label:'Activa',type:'boolean'}],
  columns:[{key:'supplier_id',label:'Proveedor',relation:{table:'suppliers',label:'name'}},{key:'concept',label:'Concepto'},{key:'unit',label:'Unidad'},{key:'unit_price',label:'Tarifa',kind:'money'},{key:'valid_from',label:'Desde',kind:'date'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 supplier_services:{table:'supplier_services',title:'Horas y servicios',singular:'servicio',fields:[
  {name:'supplier_id',label:'Proveedor / contratista',type:'select',required:true,relation:{table:'suppliers',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'service_date',label:'Fecha',type:'date',required:true},{name:'concept',label:'Concepto',required:true},{name:'quantity',label:'Cantidad',type:'number',required:true},{name:'unit',label:'Unidad'},{name:'unit_price',label:'Precio unitario',type:'number',required:true},{name:'status',label:'Estado',type:'select',options:['pendiente','aprobado','rechazado'].map(x=>({value:x,label:x}))},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'service_date',label:'Fecha',kind:'date'},{key:'supplier_id',label:'Contratista',relation:{table:'suppliers',label:'name'}},{key:'work_id',label:'Obra',relation:{table:'works',label:'name'}},{key:'concept',label:'Concepto'},{key:'quantity',label:'Cant.'},{key:'unit_price',label:'Tarifa',kind:'money'},{key:'total_amount',label:'Importe',kind:'money'},{key:'status',label:'Estado',kind:'status'}]},
 materials:{table:'materials',title:'Materiales',singular:'material',fields:[
  {name:'code',label:'Código'},{name:'name',label:'Material',required:true},{name:'description',label:'Descripción',type:'textarea'},{name:'category',label:'Categoría'},{name:'unit',label:'Unidad',required:true},{name:'minimum_stock',label:'Stock mínimo',type:'number'},{name:'current_cost',label:'Costo actual',type:'number'},{name:'is_active',label:'Activo',type:'boolean'}],
  columns:[{key:'code',label:'Código'},{key:'name',label:'Material'},{key:'category',label:'Categoría'},{key:'unit',label:'Unidad'},{key:'minimum_stock',label:'Mínimo'},{key:'current_cost',label:'Costo',kind:'money'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 stock_movements:{table:'stock_movements',title:'Movimientos de stock',singular:'movimiento',fields:[
  {name:'material_id',label:'Material',type:'select',required:true,relation:{table:'materials',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'supplier_id',label:'Proveedor',type:'select',relation:{table:'suppliers',label:'name'}},{name:'purchase_id',label:'Compra',type:'select',relation:{table:'purchases',label:'purchase_number'}},{name:'movement_type',label:'Tipo',type:'select',required:true,options:['ingreso','egreso','ajuste_positivo','ajuste_negativo'].map(x=>({value:x,label:x.replaceAll('_',' ')}))},{name:'quantity',label:'Cantidad',type:'number',required:true},{name:'unit_cost',label:'Costo unitario',type:'number'},{name:'movement_date',label:'Fecha',type:'date',required:true},{name:'reference',label:'Referencia'},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'movement_date',label:'Fecha',kind:'date'},{key:'movement_type',label:'Tipo',kind:'status'},{key:'material_id',label:'Material',relation:{table:'materials',label:'name'}},{key:'quantity',label:'Cantidad'},{key:'unit_cost',label:'Costo u.',kind:'money'},{key:'total_cost',label:'Total',kind:'money'},{key:'work_id',label:'Obra',relation:{table:'works',label:'name'}}]},
 purchases:{table:'purchases',title:'Compras',singular:'compra',fields:[
  {name:'supplier_id',label:'Proveedor',type:'select',required:true,relation:{table:'suppliers',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'purchase_number',label:'N° compra / factura'},{name:'purchase_date',label:'Fecha',type:'date',required:true},{name:'due_date',label:'Vencimiento',type:'date'},{name:'status',label:'Estado',type:'select',options:['pendiente','recibida','cancelada'].map(x=>({value:x,label:x}))},{name:'subtotal',label:'Subtotal',type:'number'},{name:'tax_amount',label:'Impuestos',type:'number'},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'purchase_number',label:'Compra'},{key:'supplier_id',label:'Proveedor',relation:{table:'suppliers',label:'name'}},{key:'work_id',label:'Obra',relation:{table:'works',label:'name'}},{key:'purchase_date',label:'Fecha',kind:'date'},{key:'due_date',label:'Vence',kind:'date'},{key:'total_amount',label:'Total',kind:'money'},{key:'status',label:'Estado',kind:'status'}]},
 purchase_items:{table:'purchase_items',title:'Ítems de compra',singular:'ítem',fields:[
  {name:'purchase_id',label:'Compra',type:'select',required:true,relation:{table:'purchases',label:'purchase_number'}},{name:'material_id',label:'Material',type:'select',relation:{table:'materials',label:'name'}},{name:'description',label:'Descripción',required:true},{name:'quantity',label:'Cantidad',type:'number',required:true},{name:'unit',label:'Unidad',required:true},{name:'unit_price',label:'Precio unitario',type:'number',required:true}],
  columns:[{key:'purchase_id',label:'Compra',relation:{table:'purchases',label:'purchase_number'}},{key:'material_id',label:'Material',relation:{table:'materials',label:'name'}},{key:'description',label:'Descripción'},{key:'quantity',label:'Cantidad'},{key:'unit_price',label:'Precio u.',kind:'money'},{key:'total_amount',label:'Total',kind:'money'}]},
 accounts:{table:'accounts',title:'Cuentas',singular:'cuenta',fields:[
  {name:'name',label:'Cuenta',required:true},{name:'type',label:'Tipo',type:'select',options:['banco','efectivo','billetera','dolares','otro'].map(x=>({value:x,label:x}))},{name:'currency',label:'Moneda',type:'select',options:[{value:'ARS',label:'ARS'},{value:'USD',label:'USD'}]},{name:'initial_balance',label:'Saldo inicial',type:'number'},{name:'is_active',label:'Activa',type:'boolean'}],
  columns:[{key:'name',label:'Cuenta'},{key:'type',label:'Tipo'},{key:'currency',label:'Moneda'},{key:'initial_balance',label:'Saldo inicial',kind:'money'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 receivables:{table:'receivables',title:'Cuentas por cobrar',singular:'cuenta por cobrar',fields:[
  {name:'client_id',label:'Cliente',type:'select',required:true,relation:{table:'clients',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'description',label:'Concepto',required:true},{name:'document_number',label:'Factura / documento'},{name:'issue_date',label:'Emisión',type:'date'},{name:'due_date',label:'Vencimiento',type:'date'},{name:'amount',label:'Monto',type:'number',required:true},{name:'status',label:'Estado',type:'select',options:['pendiente','parcial','cobrado','anulado'].map(x=>({value:x,label:x}))},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'client_id',label:'Cliente',relation:{table:'clients',label:'name'}},{key:'description',label:'Concepto'},{key:'document_number',label:'Documento'},{key:'due_date',label:'Vence',kind:'date'},{key:'amount',label:'Monto',kind:'money'},{key:'status',label:'Estado',kind:'status'}]},
 payables:{table:'payables',title:'Cuentas por pagar',singular:'cuenta por pagar',fields:[
  {name:'supplier_id',label:'Proveedor',type:'select',relation:{table:'suppliers',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'purchase_id',label:'Compra',type:'select',relation:{table:'purchases',label:'purchase_number'}},{name:'supplier_service_id',label:'Servicio contratista',type:'select',relation:{table:'supplier_services',label:'concept'}},{name:'description',label:'Concepto',required:true},{name:'document_number',label:'Documento'},{name:'issue_date',label:'Emisión',type:'date'},{name:'due_date',label:'Vencimiento',type:'date'},{name:'amount',label:'Monto',type:'number',required:true},{name:'category',label:'Categoría'},{name:'status',label:'Estado',type:'select',options:['pendiente','parcial','pagado','anulado'].map(x=>({value:x,label:x}))},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'supplier_id',label:'Proveedor',relation:{table:'suppliers',label:'name'}},{key:'description',label:'Concepto'},{key:'category',label:'Categoría'},{key:'due_date',label:'Vence',kind:'date'},{key:'amount',label:'Monto',kind:'money'},{key:'status',label:'Estado',kind:'status'}]},
 financial_movements:{table:'financial_movements',title:'Movimientos de caja',singular:'movimiento financiero',fields:[
  {name:'account_id',label:'Cuenta',type:'select',required:true,relation:{table:'accounts',label:'name'}},{name:'work_id',label:'Obra',type:'select',relation:{table:'works',label:'name'}},{name:'client_id',label:'Cliente',type:'select',relation:{table:'clients',label:'name'}},{name:'supplier_id',label:'Proveedor',type:'select',relation:{table:'suppliers',label:'name'}},{name:'receivable_id',label:'Cuenta por cobrar',type:'select',relation:{table:'receivables',label:'description'}},{name:'payable_id',label:'Cuenta por pagar',type:'select',relation:{table:'payables',label:'description'}},{name:'type',label:'Tipo',type:'select',required:true,options:['ingreso','egreso','transferencia'].map(x=>({value:x,label:x}))},{name:'category',label:'Categoría'},{name:'description',label:'Descripción',required:true},{name:'amount',label:'Monto',type:'number',required:true},{name:'movement_date',label:'Fecha',type:'date',required:true},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'movement_date',label:'Fecha',kind:'date'},{key:'type',label:'Tipo',kind:'status'},{key:'account_id',label:'Cuenta',relation:{table:'accounts',label:'name'}},{key:'description',label:'Concepto'},{key:'amount',label:'Monto',kind:'money'},{key:'work_id',label:'Obra',relation:{table:'works',label:'name'}}]},
 fixed_costs:{table:'fixed_costs',title:'Costos fijos',singular:'costo fijo',fields:[
  {name:'name',label:'Concepto',required:true},{name:'category',label:'Categoría'},{name:'amount',label:'Monto',type:'number',required:true},{name:'frequency',label:'Frecuencia',type:'select',options:['mensual','bimestral','trimestral','semestral','anual'].map(x=>({value:x,label:x}))},{name:'due_day',label:'Día de vencimiento',type:'number'},{name:'supplier_id',label:'Proveedor',type:'select',relation:{table:'suppliers',label:'name'}},{name:'is_active',label:'Activo',type:'boolean'},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'name',label:'Concepto'},{key:'category',label:'Categoría'},{key:'amount',label:'Monto',kind:'money'},{key:'frequency',label:'Frecuencia'},{key:'due_day',label:'Día pago'},{key:'is_active',label:'Estado',kind:'boolean'}]},
 work_progress:{table:'work_progress',title:'Avances de obra',singular:'avance',fields:[
  {name:'work_id',label:'Obra',type:'select',required:true,relation:{table:'works',label:'name'}},{name:'progress_date',label:'Fecha',type:'date',required:true},{name:'physical_progress_percent',label:'Avance físico %',type:'number',required:true},{name:'description',label:'Descripción'},{name:'notes',label:'Notas',type:'textarea'}],
  columns:[{key:'progress_date',label:'Fecha',kind:'date'},{key:'work_id',label:'Obra',relation:{table:'works',label:'name'}},{key:'physical_progress_percent',label:'Avance',kind:'percent'},{key:'description',label:'Descripción'}]}
};
