from pathlib import Path
ROOT=Path.cwd()
p=ROOT/'front/src/components/Planning.tsx'
t=p.read_text(encoding='utf-8')
old='const map=new Map<string,{id:string;name:string;client:string;start_date:any;end_date:any;rows:any[]}>();'
new='const map=new Map<string,{id:string;name:string;client:string;start_date:any;end_date:any;progress_percent:number;rows:any[]}>();'
if old in t: t=t.replace(old,new,1)
old="    map.set(String(w.id),{\n     id:String(w.id),\n     name:w.name||'Obra',\n     client:w.client_name||'',\n     start_date:w.start_date||null,\n     end_date:w.end_date||null,\n     rows:[]\n    });"
new="    map.set(String(w.id),{\n     id:String(w.id),\n     name:w.name||'Obra',\n     client:w.client_name||'',\n     start_date:w.start_date||null,\n     end_date:w.end_date||null,\n     progress_percent:Number(w.progress_percent||0),\n     rows:[]\n    });"
if old not in t: raise SystemExit('ERROR: alta de obras no encontrada')
t=t.replace(old,new,1)
old="    map.set(key,{\n     id:key,\n     name:r.work_name||'Obra',\n     client:r.client_name||'',\n     start_date:knownWork?.start_date||null,\n     end_date:knownWork?.end_date||null,\n     rows:[]\n    });"
new="    map.set(key,{\n     id:key,\n     name:r.work_name||'Obra',\n     client:r.client_name||'',\n     start_date:knownWork?.start_date||null,\n     end_date:knownWork?.end_date||null,\n     progress_percent:Number(knownWork?.progress_percent||0),\n     rows:[]\n    });"
if old in t: t=t.replace(old,new,1)
old=' const todayLeft=Math.min(100,Math.max(0,diffDays(today,timelineStart)/totalDays*100));\n\n const months:{label:string;span:number}[]=[];'
new=' const todayLeft=Math.min(100,Math.max(0,diffDays(today,timelineStart)/totalDays*100));\n const todayX=450+(todayLeft/100)*(weeks.length*GANTT_WEEK_PX);\n\n const months:{label:string;span:number}[]=[];'
if old not in t: raise SystemExit('ERROR: todayLeft no encontrado')
t=t.replace(old,new,1)
t=t.replace('{today>=timelineStart&&today<=timelineEnd&&<div className="gantt-today-line" style={{left:`${todayLeft}%`}}><span>Hoy</span></div>}', '')
t=t.replace('<div className="gantt-today-line" style={{left:`${todayLeft}%`}}><span>Hoy</span></div>', '')
old='   <div className="gantt-pro-table" style={{\'--gantt-timeline-width\':`${weeks.length*GANTT_WEEK_PX}px`} as any}>\n    <div className="gantt-pro-head gantt-pro-grid">'
new='   <div className="gantt-pro-table gantt-global-today-host" style={{\'--gantt-timeline-width\':`${weeks.length*GANTT_WEEK_PX}px`} as any}>\n    {today>=timelineStart&&today<=timelineEnd&&<div className="gantt-today-global" style={{left:`${todayX}px`}}><span>Hoy</span></div>}\n    <div className="gantt-pro-head gantt-pro-grid">'
if old not in t: raise SystemExit('ERROR: gantt-pro-table no encontrado')
t=t.replace(old,new,1)
start_marker='    {groups.map((g,gi)=><div className="gantt-group" key={gi}>'
task_marker='     {g.rows.map((r:any)=>{'
start=t.find(start_marker)
task_pos=t.find(task_marker,start)
if start<0 or task_pos<0: raise SystemExit('ERROR: render de grupos no encontrado')
t=t[:start]+'    {groups.map((g,gi)=><div className="gantt-group" key={gi}>\n     {parseDate(g.start_date)&&parseDate(g.end_date)?(()=>{\n      const ws=parseDate(g.start_date)!;const we=parseDate(g.end_date)!;\n      const workLeft=diffDays(ws,timelineStart)/totalDays*100;\n      const workWidth=Math.max(1.3,(diffDays(we,ws)+1)/totalDays*100);\n      const workProgress=Math.max(0,Math.min(100,Number(g.progress_percent||0)));\n      return <div className="gantt-work-main-row gantt-pro-grid">\n       <div className="gantt-work-main-info">\n        <span className="gantt-group-kicker">OBRA</span>\n        <b>{g.name}</b>\n        <small>{g.client}</small>\n        <div className="gantt-work-main-meta"><span>{fmtDate(g.start_date)} → {fmtDate(g.end_date)}</span><strong>{Math.round(workProgress)}% ejecutado</strong></div>\n       </div>\n       <div className="gantt-work-main-track">\n        <div className="gantt-work-main-bar" style={{left:`${workLeft}%`,width:`${workWidth}%`}}>\n         <div className="gantt-work-main-fill" style={{width:`${workProgress}%`}}/>\n         <div className="gantt-work-main-label"><span>{fmtDate(g.start_date)}</span><b>{Math.round(workProgress)}%</b><span>{fmtDate(g.end_date)}</span></div>\n        </div>\n       </div>\n      </div>\n     })():<div className="gantt-work-main-row gantt-pro-grid">\n      <div className="gantt-work-main-info">\n       <span className="gantt-group-kicker">OBRA</span><b>{g.name}</b><small>{g.client}</small>\n       <div className="gantt-work-main-meta"><span>Sin fecha de inicio / fin</span><strong>{Math.round(Number(g.progress_percent||0))}% ejecutado</strong></div>\n      </div>\n      <div className="gantt-work-main-track gantt-work-no-dates"><span>Cargá Inicio y Fin en Obras</span></div>\n     </div>}\n'+t[task_pos:]
p.write_text(t,encoding='utf-8')
p=ROOT/'front/app/globals.css'
css=p.read_text(encoding='utf-8')
if '/* GANTT OBRA FILA UNICA + HOY GLOBAL */' not in css:
    css+='\n/* GANTT OBRA FILA UNICA + HOY GLOBAL */\n.gantt-global-today-host{position:relative!important}\n.gantt-today-global{position:absolute;top:0;bottom:0;width:2px;background:#4f8cff;z-index:20;pointer-events:none}\n.gantt-today-global span{position:sticky;top:4px;transform:translateX(-50%);display:inline-block;background:#edf4ff;color:#2463eb;border-radius:6px;padding:2px 6px;font-size:10px;font-weight:900;white-space:nowrap;box-shadow:0 1px 3px rgba(15,23,42,.08)}\n.gantt-work-main-row{min-height:82px;background:#eaf1fb;border-top:2px solid #cdd9e8;border-bottom:1px solid #cdd9e8;position:relative;z-index:2}\n.gantt-work-main-info{padding:12px 22px;display:grid;align-content:center;gap:2px;background:#eaf1fb}\n.gantt-work-main-info>b{font-size:15px;color:#0f2747;letter-spacing:.01em}\n.gantt-work-main-info>small{font-size:11px;color:#62748b;font-weight:600}\n.gantt-work-main-meta{display:flex;gap:12px;align-items:center;margin-top:5px;font-size:11px;color:#53657b}\n.gantt-work-main-meta strong{color:#245fc1;font-size:11px}\n.gantt-work-main-track{position:relative;min-height:82px;width:var(--gantt-timeline-width);min-width:var(--gantt-timeline-width);background:#edf3fa;overflow:hidden}\n.gantt-work-main-bar{position:absolute;top:23px;height:36px;border:2px solid #5e7696;border-radius:9px;background:#dbe5f1;overflow:hidden;min-width:18px;z-index:4}\n.gantt-work-main-fill{position:absolute;inset:0 auto 0 0;background:rgba(47,111,226,.34);border-right:1px solid rgba(47,111,226,.6)}\n.gantt-work-main-label{position:absolute;inset:0;display:flex;align-items:center;justify-content:space-between;gap:8px;padding:0 9px;color:#243a56;font-size:10px;font-weight:700;white-space:nowrap}\n.gantt-work-main-label b{font-size:11px;color:#0e4fae}\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row){min-height:56px!important;background:#fff!important;border-bottom:1px solid #edf1f5}\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row) .gantt-row-info{min-height:56px!important;padding:8px 16px 8px 48px!important;background:#fff!important}\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row) .gantt-task-title{font-size:13px!important}\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row) .gantt-task-meta{margin-top:3px!important;gap:6px!important}\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row) .gantt-row-track-wrap,\n.gantt-group .gantt-row-pro:not(.gantt-work-main-row) .gantt-row-track{min-height:56px!important}\n.gantt-group{border-top:0!important}\n.gantt-group-title,.gantt-work-span-row{display:none!important}\n.gantt-row-pro .gantt-today-line,.gantt-work-track .gantt-today-line{display:none!important}\n'
p.write_text(css,encoding='utf-8')
print('OK: obra/plazo/avance unificados, tareas compactas y Hoy continuo.')