from pathlib import Path
p=Path.cwd()/'front/src/components/Planning.tsx'
t=p.read_text(encoding='utf-8')
old=' const groups=useMemo(()=>{\n  const workMap=new Map((works||[]).map((w:any)=>[w.id,w]));\n  const map=new Map<string,{id:string;name:string;client:string;start_date:any;end_date:any;rows:any[]}>();\n  dated.forEach((r:any)=>{\n   const key=r.work_id||r.work_name||\'obra\';\n   const w=workMap.get(r.work_id);\n   if(!map.has(key))map.set(key,{id:String(r.work_id||key),name:r.work_name||w?.name||\'Obra\',client:r.client_name||\'\',start_date:w?.start_date||null,end_date:w?.end_date||null,rows:[]});\n   map.get(key)!.rows.push(r);\n  });\n  const list=Array.from(map.values());\n  list.forEach(g=>g.rows.sort((a:any,b:any)=>(parseDate(a.start_date)?.getTime()||0)-(parseDate(b.start_date)?.getTime()||0)));\n  return list;\n },[dated,works]);\n\n if(!dated.length)return <Empty text="Cargá fechas de inicio y fin para visualizar el cronograma."/>;\n'
new=' const groups=useMemo(()=>{\n  const map=new Map<string,{id:string;name:string;client:string;start_date:any;end_date:any;rows:any[]}>();\n\n  // Primero incorporamos TODAS las obras, aunque todavía no tengan tareas.\n  (works||[])\n   .filter((w:any)=>String(w.type||\'obra\')!==\'servicio_mensual\')\n   .forEach((w:any)=>{\n    map.set(String(w.id),{\n     id:String(w.id),\n     name:w.name||\'Obra\',\n     client:w.client_name||\'\',\n     start_date:w.start_date||null,\n     end_date:w.end_date||null,\n     rows:[]\n    });\n   });\n\n  // Después agregamos las tareas con fecha dentro de su obra.\n  dated.forEach((r:any)=>{\n   const key=String(r.work_id||r.work_name||\'obra\');\n   if(!map.has(key)){\n    map.set(key,{\n     id:key,\n     name:r.work_name||\'Obra\',\n     client:r.client_name||\'\',\n     start_date:null,\n     end_date:null,\n     rows:[]\n    });\n   }\n   const g=map.get(key)!;\n   if(!g.client&&r.client_name)g.client=r.client_name;\n   g.rows.push(r);\n  });\n\n  const list=Array.from(map.values());\n  list.forEach(g=>g.rows.sort((a:any,b:any)=>(parseDate(a.start_date)?.getTime()||0)-(parseDate(b.start_date)?.getTime()||0)));\n  list.sort((a:any,b:any)=>{\n   const ad=parseDate(a.start_date)?.getTime()??Number.MAX_SAFE_INTEGER;\n   const bd=parseDate(b.start_date)?.getTime()??Number.MAX_SAFE_INTEGER;\n   return ad-bd||a.name.localeCompare(b.name,\'es\');\n  });\n  return list;\n },[dated,works]);\n\n const datedWorks=groups.filter((g:any)=>parseDate(g.start_date)&&parseDate(g.end_date));\n if(!dated.length&&!datedWorks.length)return <Empty text="Cargá fechas de inicio y fin en las obras o en sus tareas para visualizar el cronograma."/>;\n'
if old not in t: raise SystemExit('ERROR: bloque groups actual no encontrado')
t=t.replace(old,new,1)
old=' const workStarts=groups.map((g:any)=>parseDate(g.start_date)?.getTime()).filter((x:any)=>Number.isFinite(x));\n const workEnds=groups.map((g:any)=>parseDate(g.end_date)?.getTime()).filter((x:any)=>Number.isFinite(x));\n'
new=' const workStarts=datedWorks.map((g:any)=>parseDate(g.start_date)!.getTime());\n const workEnds=datedWorks.map((g:any)=>parseDate(g.end_date)!.getTime());\n'
if old not in t: raise SystemExit('ERROR: fechas de obras no encontradas')
t=t.replace(old,new,1)
old='     {parseDate(g.start_date)&&parseDate(g.end_date)&&(()=>{\n      const ws=parseDate(g.start_date)!;const we=parseDate(g.end_date)!;\n      const workLeft=diffDays(ws,timelineStart)/totalDays*100;\n      const workWidth=Math.max(1.3,(diffDays(we,ws)+1)/totalDays*100);\n      return <div className="gantt-row-pro gantt-pro-grid gantt-work-span-row">\n       <div className="gantt-row-info"><div className="gantt-task-title">Plazo de obra</div><div className="gantt-task-meta"><span>{fmtDate(g.start_date)} → {fmtDate(g.end_date)}</span></div></div>\n       <div className="gantt-track gantt-work-track"><div className="gantt-work-span" style={{left:`${workLeft}%`,width:`${workWidth}%`}}><span>{fmtDate(g.start_date)}</span><b>{g.name}</b><span>{fmtDate(g.end_date)}</span></div>{today>=timelineStart&&today<=timelineEnd&&<div className="gantt-today-line" style={{left:`${todayLeft}%`}}><span>Hoy</span></div>}</div>\n      </div>\n     })()}\n'
new='     {parseDate(g.start_date)&&parseDate(g.end_date)?(()=>{\n      const ws=parseDate(g.start_date)!;const we=parseDate(g.end_date)!;\n      const workLeft=diffDays(ws,timelineStart)/totalDays*100;\n      const workWidth=Math.max(1.3,(diffDays(we,ws)+1)/totalDays*100);\n      return <div className="gantt-row-pro gantt-pro-grid gantt-work-span-row">\n       <div className="gantt-row-info"><div className="gantt-task-title">Plazo de obra</div><div className="gantt-task-meta"><span>{fmtDate(g.start_date)} → {fmtDate(g.end_date)}</span></div></div>\n       <div className="gantt-track gantt-work-track"><div className="gantt-work-span" style={{left:`${workLeft}%`,width:`${workWidth}%`}}><span>{fmtDate(g.start_date)}</span><b>{g.name}</b><span>{fmtDate(g.end_date)}</span></div>{today>=timelineStart&&today<=timelineEnd&&<div className="gantt-today-line" style={{left:`${todayLeft}%`}}><span>Hoy</span></div>}</div>\n      </div>\n     })():<div className="gantt-row-pro gantt-pro-grid gantt-work-span-row">\n      <div className="gantt-row-info"><div className="gantt-task-title">Plazo de obra</div><div className="gantt-task-meta"><span>Sin fecha de inicio / fin cargada</span></div></div>\n      <div className="gantt-track gantt-work-track gantt-work-no-dates"><span>Cargá las fechas en Obras para visualizar el plazo</span></div>\n     </div>}\n'
if old not in t: raise SystemExit('ERROR: fila Plazo de obra no encontrada')
t=t.replace(old,new,1)
p.write_text(t,encoding='utf-8')

p=Path.cwd()/'front/app/globals.css'
css=p.read_text(encoding='utf-8')
if '/* GANTT OBRAS SIN FECHA */' not in css:
    css += '\n/* GANTT OBRAS SIN FECHA */\n.gantt-work-no-dates{display:flex;align-items:center;padding:0 14px;color:#94a3b8;font-size:12px;font-weight:600;background:#f8fafc}\n'
p.write_text(css,encoding='utf-8')
print('OK: el cronograma ahora incluye todas las obras, tengan o no tareas.')