from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]

p = ROOT / "backend/app/routers/services_board.py"
t = p.read_text(encoding="utf-8")
for old,new in [
    ('        if status == "cancelado":\n            effective_status = "cancelado"\n        elif end_date and end_date < today:\n            effective_status = "finalizado"\n        else:\n            effective_status = "activo"\n\n        days_to_end = (end_date - today).days if end_date else None\n        pending_collection = D(r.get("pending_collection"))\n        invoiced = D(r.get("invoiced_total"))\n        overdue = D(r.get("overdue_amount"))\n        pending_periods = int(r.get("pending_periods") or 0)\n        due_pending_periods = int(r.get("due_pending_periods") or 0)\n        future_pending_periods = int(r.get("future_pending_periods") or 0)\n        total_periods = int(r.get("total_periods") or 0)\n        billed_periods = int(r.get("billed_periods") or 0)\n','        days_to_end = (end_date - today).days if end_date else None\n        pending_collection = D(r.get("pending_collection"))\n        invoiced = D(r.get("invoiced_total"))\n        overdue = D(r.get("overdue_amount"))\n        pending_periods = int(r.get("pending_periods") or 0)\n        due_pending_periods = int(r.get("due_pending_periods") or 0)\n        future_pending_periods = int(r.get("future_pending_periods") or 0)\n        total_periods = int(r.get("total_periods") or 0)\n        billed_periods = int(r.get("billed_periods") or 0)\n\n        if status == "cancelado":\n            effective_status = "cancelado"\n        elif end_date and end_date < today:\n            if pending_periods <= 0 and pending_collection <= 0:\n                effective_status = "finalizado"\n            else:\n                effective_status = "pendiente_cierre"\n        else:\n            effective_status = "activo"\n'),
    ('        if effective_status == "finalizado" and pending_collection > 0:\n            score += 3\n            reasons.append("servicio finalizado con saldo pendiente")\n','        if effective_status == "pendiente_cierre":\n            score += 3\n            if due_pending_periods > 0:\n                reasons.append("vigencia terminada con períodos sin facturar")\n            if pending_collection > 0:\n                reasons.append("vigencia terminada con saldo pendiente")\n'),
    ('        if effective_status == "activo":\n            active_count += 1\n            if str(r.get("service_type") or "").lower() == "mensual":\n                recurring_monthly += D(r.get("billing_amount"))\n            pending_total += pending_collection\n            if risk == "alto":\n                high_count += 1\n','        if effective_status == "activo":\n            active_count += 1\n            if str(r.get("service_type") or "").lower() == "mensual":\n                recurring_monthly += D(r.get("billing_amount"))\n\n        if effective_status in ("activo", "pendiente_cierre"):\n            pending_total += pending_collection\n            if risk == "alto":\n                high_count += 1\n'),
]:
    if old not in t:
        raise SystemExit("ERROR: bloque esperado no encontrado en services_board.py")
    t=t.replace(old,new,1)
p.write_text(t,encoding="utf-8")

p = ROOT / "backend/app/routers/service_detail.py"
t = p.read_text(encoding="utf-8")
old="                          extract(year from (%s::date + make_interval(months => gs.i - 1)))::integer,\n                          extract(month from (%s::date + make_interval(months => gs.i - 1)))::integer,\n                          least(\n                            %s::integer,\n                            extract(day from (date_trunc('month', (%s::date + make_interval(months => gs.i - 1))) + interval '1 month - 1 day'))::integer\n                          )"; new="                          extract(year from (%s::date + make_interval(months => gs.i)))::integer,\n                          extract(month from (%s::date + make_interval(months => gs.i)))::integer,\n                          least(\n                            %s::integer,\n                            extract(day from (date_trunc('month', (%s::date + make_interval(months => gs.i))) + interval '1 month - 1 day'))::integer\n                          )"
if old not in t:
    raise SystemExit("ERROR: cálculo de fecha de facturación no encontrado")
t=t.replace(old,new,1)
p.write_text(t,encoding="utf-8")

p = ROOT / "front/src/components/ServicesBoard.tsx"
t = p.read_text(encoding="utf-8")
for old,new in [
    (" const [sort,setSort]=useState<'risk'|'end'|'pending'>('risk');\n const [selected,setSelected]=useState<string|null>(null);\n"," const [sort,setSort]=useState<'risk'|'end'|'pending'>('risk');\n const [selected,setSelected]=useState<string|null>(null);\n const [editing,setEditing]=useState<any|null>(null);\n const [editForm,setEditForm]=useState<any>({});\n const [savingEdit,setSavingEdit]=useState(false);\n"),
    (' if(selected)return <ServiceDetail serviceId={selected} onBack={()=>{setSelected(null);void load()}}/>;'," const openEdit=(r:any)=>{\n   setEditing(r);\n   setEditForm({\n     name:r.name||'',\n     billing_amount:String(r.billing_amount??''),\n     start_date:r.start_date?String(r.start_date).slice(0,10):'',\n     duration_months:String(r.duration_months??''),\n     billing_day:r.billing_day==null?'':String(r.billing_day),\n   });\n };\n\n const saveEdit=async(e:any)=>{\n   e.preventDefault();\n   if(!editing)return;\n   setSavingEdit(true);\n   try{\n     await api.update('services',editing.id,{\n       name:String(editForm.name||'').trim(),\n       billing_amount:Number(editForm.billing_amount||0),\n       start_date:editForm.start_date||null,\n       duration_months:editForm.duration_months===''?null:Number(editForm.duration_months),\n       billing_day:editForm.billing_day===''?null:Number(editForm.billing_day),\n     });\n     await api.get<any>(`/api/services/${editing.id}/detail`);\n     setEditing(null);\n     await load();\n   }catch(err:any){\n     alert(err?.message||String(err));\n   }finally{\n     setSavingEdit(false);\n   }\n };\n\n if(selected)return <ServiceDetail serviceId={selected} onBack={()=>{setSelected(null);void load()}}/>;"),
    ("     const aFinished=a.effective_status!=='activo';\n     const bFinished=b.effective_status!=='activo';","     const aFinished=['finalizado','cancelado'].includes(a.effective_status);\n     const bFinished=['finalizado','cancelado'].includes(b.effective_status);"),
    ("          return <tr key={r.id} className={`${r.effective_status!=='activo'?'finished-row':''} clickable-row`} onClick={()=>setSelected(r.id)}>","          const visuallyFinished=['finalizado','cancelado'].includes(r.effective_status);\n          return <tr key={r.id} className={`${visuallyFinished?'finished-row':''} clickable-row`} onClick={()=>setSelected(r.id)}>"),
    ('            <td><b>{r.name}</b>\n              {Number(r.due_pending_periods)>0&&<small className="work-row-note">{r.due_pending_periods} período{Number(r.due_pending_periods)===1?\'\':\'s\'} sin facturar</small>}','            <td>\n              <div style={{display:\'flex\',alignItems:\'center\',gap:8,flexWrap:\'wrap\'}}>\n                <b>{r.name}</b>\n                <button className="mini-button" onClick={e=>{e.stopPropagation();openEdit(r)}}>Editar</button>\n              </div>\n              {Number(r.due_pending_periods)>0&&<small className="work-row-note">{r.due_pending_periods} período{Number(r.due_pending_periods)===1?\'\':\'s\'} sin facturar</small>}'),
    ("<small><Status tone={r.effective_status==='activo'?'green':r.effective_status==='cancelado'?'red':'blue'}>{r.effective_status}</Status></small>","<small><Status tone={r.effective_status==='activo'?'green':r.effective_status==='pendiente_cierre'?'yellow':r.effective_status==='cancelado'?'red':'blue'}>{r.effective_status==='pendiente_cierre'?'Pendiente de cierre':r.effective_status}</Status></small>"),
    ('   </section>\n </div>\n}','   </section>\n\n   {editing&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setEditing(null)}}>\n     <div className="modal">\n       <div className="modal-head">\n         <div><span className="eyebrow">EDITAR SERVICIO</span><h2>{editing.name}</h2></div>\n         <button className="close-button" onClick={()=>setEditing(null)}>×</button>\n       </div>\n       <form onSubmit={saveEdit}>\n         <div className="form-grid">\n           <label className="field full"><span>Nombre</span><input required value={editForm.name||\'\'} onChange={e=>setEditForm({...editForm,name:e.target.value})}/></label>\n           <label className="field"><span>Monto mensual</span><input type="number" min="0" step="0.01" required value={editForm.billing_amount||\'\'} onChange={e=>setEditForm({...editForm,billing_amount:e.target.value})}/></label>\n           <label className="field"><span>Fecha de inicio</span><input type="date" value={editForm.start_date||\'\'} onChange={e=>setEditForm({...editForm,start_date:e.target.value})}/></label>\n           <label className="field"><span>Duración (meses)</span><input type="number" min="1" step="1" value={editForm.duration_months||\'\'} onChange={e=>setEditForm({...editForm,duration_months:e.target.value})}/></label>\n           <label className="field"><span>Día de facturación/cobro</span><input type="number" min="1" max="31" value={editForm.billing_day||\'\'} onChange={e=>setEditForm({...editForm,billing_day:e.target.value})}/></label>\n         </div>\n         <div className="modal-note" style={{marginTop:12}}>\n           Los cambios de monto y fechas actualizan únicamente los períodos que todavía no fueron facturados.\n         </div>\n         <div className="modal-actions">\n           <button type="button" className="ghost-button" onClick={()=>setEditing(null)}>Cancelar</button>\n           <button className="primary-button" disabled={savingEdit}>{savingEdit?\'Guardando…\':\'Guardar cambios\'}</button>\n         </div>\n       </form>\n     </div>\n   </div>}\n </div>\n}'),
]:
    if old not in t:
        raise SystemExit("ERROR: bloque esperado no encontrado en ServicesBoard.tsx")
    t=t.replace(old,new,1)

t=t.replace("Los finalizados y cancelados se muestran al final.",
            "Solo los servicios realmente cerrados se muestran atenuados y al final.")
p.write_text(t,encoding="utf-8")

print("OK: edición rápida, cierre real y mes vencido aplicados.")
