from pathlib import Path

p = Path.cwd() / 'backend/app/routers/service_documents.py'
t = p.read_text(encoding='utf-8')
old = 'async def _ensure_bucket():\n    base = settings.supabase_url.rstrip("/")\n    async with httpx.AsyncClient(timeout=30) as client:\n        r = await client.get(f"{base}/storage/v1/bucket/{BUCKET}", headers=_headers())\n        if r.status_code == 404:\n            c = await client.post(f"{base}/storage/v1/bucket", headers={**_headers("application/json")},\n                                  json={"id": BUCKET, "name": BUCKET, "public": False, "file_size_limit": 20971520})\n            if c.status_code >= 300 and c.status_code != 409:\n                raise HTTPException(502, f"No se pudo crear bucket: {c.text}")\n        elif r.status_code >= 300:\n            raise HTTPException(502, f"No se pudo consultar bucket: {r.text}")\n'
new = 'async def _ensure_bucket():\n    base = settings.supabase_url.rstrip("/")\n    async with httpx.AsyncClient(timeout=30) as client:\n        r = await client.get(\n            f"{base}/storage/v1/bucket/{BUCKET}",\n            headers=_headers(),\n        )\n\n        body = (r.text or "").lower()\n        missing = (\n            r.status_code == 404\n            or "nosuchbucket" in body\n            or "bucket not found" in body\n            or \'"code":"nosuchbucket"\' in body\n        )\n\n        if r.status_code == 200:\n            return\n\n        if not missing:\n            raise HTTPException(\n                502,\n                f"No se pudo consultar bucket \'{BUCKET}\': {r.text}",\n            )\n\n        c = await client.post(\n            f"{base}/storage/v1/bucket",\n            headers={**_headers("application/json")},\n            json={\n                "id": BUCKET,\n                "name": BUCKET,\n                "public": False,\n                "file_size_limit": 20971520,\n            },\n        )\n\n    if c.status_code in (200, 201):\n        return\n\n    create_body = (c.text or "").lower()\n    if c.status_code in (400, 409) and (\n        "already exists" in create_body\n        or "duplicate" in create_body\n        or "bucket exists" in create_body\n    ):\n        return\n\n    raise HTTPException(\n        502,\n        f"No se pudo crear bucket \'{BUCKET}\': {c.text}",\n    )\n'
if old not in t:
    raise SystemExit('ERROR: bloque _ensure_bucket de servicios no encontrado')
t = t.replace(old, new, 1)
p.write_text(t, encoding='utf-8')
print('OK: Storage de Servicios corregido para NoSuchBucket.')